kind: Service
apiVersion: v1
metadata:
  name: odyssey-jot-vault
  labels:
    app: odyssey-jot-vault
spec:
  type: NodePort
  selector:
    app: odyssey-jot-vault
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: odyssey-jot-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odyssey-jot-vault
  template:
    metadata:
      labels:
        app: odyssey-jot-vault
        version: v1
    spec:
      containers:
      - name: odyssey-jot-vault
        image: odyssey-jot-vault
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
