kind: Service
apiVersion: v1
metadata:
  name: odyssey-jotvault
  labels:
    app: odyssey-jotvault
spec:
  type: NodePort
  selector:
    app: odyssey-jotvault
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: odyssey-jotvault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odyssey-jotvault
  template:
    metadata:
      labels:
        app: odyssey-jotvault
        version: v1
    spec:
      containers:
      - name: odyssey-jotvault
        image: odyssey-jotvault
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
